#cloud-config
package_update: true
packages:
  - postgresql
  - postgresql-client
  - ec2-instance-connect
runcmd:
  - systemctl enable postgresql
  - systemctl start postgresql
  - sudo -u postgres psql -c "CREATE USER labuser WITH PASSWORD 'Lab@2024!';"
  - sudo -u postgres psql -c "CREATE DATABASE labdb OWNER labuser;"
  - sudo -u postgres psql -c "ALTER SYSTEM SET listen_addresses = '10.0.2.10';"
  - sudo -u postgres psql -c "ALTER SYSTEM SET max_connections = '20';"
  - PG_HBA_FILE=$(find /etc/postgresql -name pg_hba.conf | head -n 1)
  - echo 'host labdb labuser 10.0.1.0/24 md5' >> ${PG_HBA_FILE}
  - systemctl restart postgresql
